### ISSUE TITLE
没有找到DaggerActivityComponent这个类

### ISSUE THREAD

**Issue by LinSX2017** [borneywpf/TLRLoadRefresh#1]
想要把你的代码clone下来看一下，结果clone下来之后出现一个问题，initActivityComponent这个方法中没找到DaggerActivityComponent这个类，可以贴一下代码吗

**Comment by borneywpf** [comment]
我用的dragger，详细可见[编译配置](https://github.com/borneywpf/TLRLoadRefresh/blob/master/buildsystem/dependencies.gradle)
