### ISSUE TITLE
RecyclerView 情况下 如果禁用掉弹性滑动

### ISSUE THREAD

**Issue by Biswangluo** [borneywpf/TLRLoadRefresh#2]
拉倒底部还能往上拉，不想要这种特效，怎么禁止?

**Comment by borneywpf** [comment]
这是个bug，已经修复，具体查看[commit]，(https://github.com/borneywpf/TLRLoadRefresh/commit/a9b0c55e2da13f4e0f42b35ddb700ef6bca840a1)，感谢你的反馈，如果还有其他问题，欢迎随时提问

**Comment by borneywpf** [comment]
这是一个bug，已经修复，可查看[056e866](https://github.com/borneywpf/TLRLoadRefresh/commit/a9b0c55e2da13f4e0f42b35ddb700ef6bca840a1),感谢你的反馈，如果还有其他问题，欢迎随时提问。
